config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "kittens#index"

  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, presence: true, length: { maximum: 25 }
  validates :age, presence: true
  validates :cuteness, presence: true
  validates :softness, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render xml: @kittens }
      format.json { render json: @kittens }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash.notice = "Success: created"
      redirect_to @kitten
    else
      flash[:notice] = "Failed to save, try again"
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render xml: @kitten }
      format.json { render json: @kitten }
    end
  end

  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update(kitten_params)
      flash.notice = "Success: updated"
      redirect_to @kitten
    else
      flash.notice = "Failed to save, try again"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy
    flash.notice = "Deleted a meow"
    redirect_to root_path, status: :see_other
  end

  private
    def kitten_params
      params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with model: @kitten do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <% @kitten.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :age %>
    <%= form.number_field :age, in: 1..10, step: 1 %>
    <% @kitten.errors.full_messages_for(:age).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :cuteness %>
    <%= form.number_field :cuteness, in: 1..10, step: 1 %>
    <% @kitten.errors.full_messages_for(:cuteness).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :softness %>
    <%= form.number_field :softness, in: 1..10, step: 1 %>
  </div>
  <%= form.submit %>
  <% @kitten.errors.full_messages_for(:softness).each do |message| %>
      <div><%= message %></div>
    <% end %>
<% end %>

app/views/kittens/create.html.erb
<h1>Kittens#create</h1>
<p>Find me in app/views/kittens/create.html.erb</p>

app/views/kittens/destroy.html.erb
<h1>Kittens#destroy</h1>
<p>Find me in app/views/kittens/destroy.html.erb</p>

app/views/kittens/edit.html.erb
<h1>Edit</h1>
<%= render "form" %>

<%= link_to "Destroy", kitten_path(@kitten), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>

app/views/kittens/index.html.erb
<ul>
  <% @kittens.each do |kitten| %>
  <div>
   
    <h3><%= link_to(kitten.name, "/kittens/#{kitten.id}") %></h3>
    <li>
      Age : <%= kitten.age %> months
    </li>
    <li>
      Cuteness : <%= kitten.cuteness %>
    </li>
    <li>
      Softness : <%= kitten.softness %>
    </li>
    <%= link_to "Destroy", kitten_path(kitten), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
  </div>
  <% end %>
</ul>

app/views/kittens/new.html.erb
<h1>Create new kitten</h1>
<%= render "form" %>

app/views/kittens/show.html.erb
<h3>    <%= @kitten.name %>                  </h3>
<h3>    Age : <%= @kitten.age %> months       </h3>
<h3>    Cuteness : <%= @kitten.cuteness %>    </h3>
<h3>    Softness : <%= @kitten.softness %>    </h3>

<%= link_to "Edit me", edit_kitten_path(@kitten) %>
<%= link_to "Destroy", kitten_path(@kitten), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>

app/views/kittens/update.html.erb
<h1>Kittens#update</h1>
<p>Find me in app/views/kittens/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Odin Kitten Api" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%# Flash %>
    <% if flash[:alert] %>
      <div class="alert"><%= flash[:alert] %></div>
    <% end %>
    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>

    <h1><%= link_to "Kitten", root_path %></h1>
    <h3><%= link_to "Create new kitten", new_kitten_path %></h3>

    <%# Main body %>
    <%= yield %>
  </body>
</html>